version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: anonymous_db
    ports:
      - "5432:5432"
    restart: always
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  matchmaker:
    build: .
    command: node matchmaker.js
    ports:
      - "3001:3001"
    depends_on:
      - redis
    restart: always

  worker:
    build: .
    command: node worker.js
    depends_on:
      - postgres
      - redis
    restart: always

  node_a:
    build: .
    command: node server.js 8081
    depends_on:
      - redis
      - matchmaker
    restart: always

  node_b:
    build: .
    command: node server.js 8082
    depends_on:
      - redis
      - matchmaker
    restart: always

  node_c:
    build: .
    command: node server.js 8083
    depends_on:
      - redis
      - matchmaker
    restart: always

  loadbalancer:
    build: .
    command: node loadbalancer.js
    ports:
      - "8080:8080" # Exposed entry point for k6 and external connections
    depends_on:
      - node_a
      - node_b
      - node_c
    restart: always